### ISSUE TITLE
PHP Error: Failed to load plugin file

### ISSUE THREAD

**Issue by wbiehl** [SS88UK/roundcube-easy-unsubscribe#8]
After installation the log floods with the following error record

PHP Error: Failed to load plugin file /usr/local/lib/roundcubemail/plugins/easy-unsubscribe/easy-unsubscribe.php in /usr/local/lib/roundcubemail/program/lib/Roundcube/rcube_plugin_api.php on line 193 (POST /mail/?_task=mail&_action=refresh)

**Comment by Neoboffin** [comment]
Hi @wbiehl,

Did you install this via composer? I think I've added it incorrectly to Github in relation to Composer.

**Comment by wbiehl** [comment]
Yes, I installed it via composer.

**Comment by Neoboffin** [comment]
Hi @wbiehl,

Sorry this took a while, I have just got around to testing with composer. When adding to `composer.json` and updating, it downloads and installs the plugin into the folder `plugins/easy_unsubscribe` (take note of the underscore).

In your `config.inc.php` file, are you using underscores (_) instead of a dash?
